import type { BlogSection } from "./blogs";

export const blogExtensions: Record<string, BlogSection[]> = {
  "the-art-of-long-fermentation": [
    {
      heading: { tr: "Soğuk, süreci durdurmaz; düzenler", en: "Cold does not stop the process; it shapes it", de: "Kälte stoppt den Prozess nicht, sie ordnet ihn", fr: "Le froid n’arrête pas le processus, il l’ordonne", ar: "البرودة لا توقف العملية بل تنظّمها", ru: "Холод не останавливает процесс, а направляет его" },
      body: {
        tr: "Soğuk fermantasyon mayanın hızını düşürürken aromanın katmanlanmasına zaman tanır. Ancak buzdolabı tek başına iyi hamur üretmez: hamurun iç sıcaklığı, kapların yerleşimi ve son dinlendirme süresi birlikte okunmalıdır. Fırına girecek hamurun canlı, esnek ve yüzey gerilimini koruyor olması gerekir. Fazla soğuk hamur açılırken direnir; fazla ısınan hamur ise gücünü kaybeder. Ustalık, iki uç arasında doğru servis penceresini bulmaktır.",
        en: "Cold fermentation slows the yeast and gives flavour time to layer, but a refrigerator alone cannot make good dough. Core temperature, tray position and the final rest must be read together. Dough approaching the oven should feel lively, supple and still hold surface tension. Too cold and it resists opening; too warm and it loses strength. Craft lies in finding the calm service window between those extremes.",
        de: "Kalte Fermentation bremst die Hefe und gibt dem Aroma Zeit, doch ein Kühlschrank allein erzeugt keinen guten Teig. Kerntemperatur, Position der Behälter und letzte Ruhephase müssen gemeinsam gelesen werden. Der Teig soll lebendig, geschmeidig und gespannt zum Ofen kommen. Zu kalt wehrt er sich beim Öffnen, zu warm verliert er Kraft. Handwerk heißt, das ruhige Fenster dazwischen zu finden.",
        fr: "La fermentation au froid ralentit la levure et laisse les arômes se superposer, mais un réfrigérateur ne suffit pas à créer une bonne pâte. Température à cœur, place des bacs et repos final se lisent ensemble. À l’approche du four, la pâte doit rester vivante, souple et tendue. Trop froide, elle résiste ; trop chaude, elle perd sa force. Le geste consiste à trouver la juste fenêtre de service.",
        ar: "يخفّض التخمير البارد سرعة الخميرة ويمنح النكهة وقتاً لتتراكم، لكن الثلاجة وحدها لا تصنع عجيناً جيداً. يجب قراءة حرارة الداخل ومكان الصواني وراحة العجين الأخيرة معاً. ينبغي أن يصل العجين إلى الفرن حياً ومرناً ومحافظاً على شدّه؛ فالبرودة الزائدة تجعله يقاوم والدفء الزائد يضعفه. الحرفة هي العثور على اللحظة الهادئة بينهما.",
        ru: "Холодная ферментация замедляет дрожжи и даёт вкусу время стать многослойным, но один холодильник хорошего теста не создаёт. Внутреннюю температуру, расположение контейнеров и финальный отдых оценивают вместе. Перед печью тесто должно быть живым, гибким и сохранять натяжение: слишком холодное сопротивляется, слишком тёплое теряет силу. Мастерство — найти точное окно между ними.",
      },
    },
    {
      heading: { tr: "Olgun hamurun sofradaki karşılığı", en: "What mature dough brings to the table", de: "Was reifer Teig auf den Tisch bringt", fr: "Ce que la pâte mûre apporte à table", ar: "ما يقدمه العجين الناضج للمائدة", ru: "Что зрелое тесто приносит к столу" },
      body: {
        tr: "Doğru olgunlaşmış hamur yalnızca büyük hava gözleriyle kendini göstermez. Isırıldığında ince bir çıtırtının ardından nemli ve ipeksi bir iç doku gelir; kavrulmuş tahıl, süt ve hafif fındıksı aromalar sosun gerisinde kaybolmaz. Kenar çiğnemeyi yormaz, merkez ise malzemeyi taşır. Bizim için uzun fermantasyonun gerçek başarısı fotoğraftaki hacim değil, son lokmaya kadar korunan hafiflik ve dengedir.",
        en: "Properly matured dough is not defined by large air pockets alone. A fine crackle gives way to a moist, silky crumb; toasted grain, dairy and faint nutty notes remain audible beneath the sauce. The rim never tires the jaw and the centre still carries its topping. For us, the proof of long fermentation is not volume in a photograph but lightness and balance that survive to the final bite.",
        de: "Reifer Teig zeigt sich nicht nur in großen Poren. Auf feines Knacken folgt eine feuchte, seidige Krume; geröstetes Korn, Milchigkeit und nussige Noten bleiben unter der Sauce erkennbar. Der Rand ermüdet nicht, die Mitte trägt den Belag. Für uns beweist lange Fermentation sich nicht im Fotovolumen, sondern in Leichtigkeit und Balance bis zum letzten Bissen.",
        fr: "Une pâte mûre ne se résume pas à de grandes alvéoles. Un craquant fin précède une mie humide et soyeuse ; le grain toasté, le lait et une nuance de noisette restent perceptibles sous la sauce. La corniche ne fatigue pas et le centre porte la garniture. La réussite se mesure moins au volume de la photo qu’à la légèreté conservée jusqu’à la dernière bouchée.",
        ar: "لا يُقاس نضج العجين بالفقاعات الكبيرة وحدها. تأتي قرمشة رقيقة قبل لبّ رطب وحريري، وتبقى روائح الحبوب المحمصة والحليب ولمحة البندق واضحة تحت الصلصة. لا تتعب الحافة الفم ويحمل الوسط الإضافات بثبات. نجاح التخمير الطويل عندنا هو الخفة والتوازن حتى اللقمة الأخيرة، لا الحجم في الصورة.",
        ru: "Зрелое тесто узнаётся не только по крупным порам. За тонким хрустом следует влажный шелковистый мякиш; под соусом остаются ноты жареного зерна, молока и ореха. Бортик не утомляет, а центр удерживает начинку. Для нас успех долгой ферментации — не объём на фотографии, а лёгкость и баланс до последнего кусочка.",
      },
    },
  ],
  "from-flour-to-fire": [
    {
      heading: { tr: "Açmak, havayı yönlendirmektir", en: "Opening dough means guiding the air", de: "Teig öffnen heißt Luft lenken", fr: "Ouvrir la pâte, c’est guider l’air", ar: "فتح العجين هو توجيه الهواء", ru: "Раскрыть тесто — значит направить воздух" },
      body: {
        tr: "Hamur merdaneyle ezilmez; merkezden dışarıya doğru parmak uçlarıyla açılır. Amaç içteki gazı yok etmek değil, onu kenara doğru yönlendirerek cornicione’yi beslemektir. Her hareket un miktarını, tezgâh sürtünmesini ve hamurun geri toplanma eğilimini hesaba katar. Gereğinden fazla müdahale hamuru inceltir; az müdahale ise kalın ve ağır bir merkez bırakır. Doğru kalınlık gözden çok elin hafızasıyla bulunur.",
        en: "The dough is never crushed with a rolling pin; fingertips open it from the centre out. The aim is not to expel its gas but to guide it toward the rim and feed the cornicione. Every motion accounts for flour, bench friction and the dough’s tendency to spring back. Too much handling thins and weakens it; too little leaves a heavy centre. The right thickness is found through the memory of the hands as much as the eye.",
        de: "Der Teig wird nicht mit dem Nudelholz zerdrückt, sondern mit den Fingerspitzen von innen nach außen geöffnet. Die Luft soll nicht verschwinden, sondern zum Rand wandern und die Cornicione nähren. Jede Bewegung berücksichtigt Mehl, Reibung und Rückzugskraft. Zu viel Berührung schwächt, zu wenig lässt eine schwere Mitte. Die richtige Stärke findet vor allem das Gedächtnis der Hände.",
        fr: "La pâte n’est jamais écrasée au rouleau ; les doigts l’ouvrent du centre vers l’extérieur. Il ne s’agit pas d’expulser le gaz, mais de le guider vers la corniche. Chaque mouvement tient compte de la farine, du frottement et du retour élastique. Trop manipuler affaiblit la pâte ; pas assez laisse un centre lourd. La juste épaisseur appartient autant à la mémoire des mains qu’au regard.",
        ar: "لا يُسحق العجين بالشوبك، بل يُفتح بأطراف الأصابع من المركز إلى الخارج. الهدف ليس طرد الهواء بل توجيهه إلى الحافة لتغذيتها. تراعي كل حركة مقدار الدقيق واحتكاك السطح وعودة العجين إلى شكله. كثرة اللمس تضعفه وقلّته تترك مركزاً ثقيلاً. السماكة الصحيحة تعرفها ذاكرة اليد بقدر ما تراها العين.",
        ru: "Тесто не давят скалкой: его раскрывают подушечками пальцев от центра к краю. Газ не выпускают, а направляют к корничоне. Каждое движение учитывает муку, трение стола и упругий возврат. Лишние касания ослабляют заготовку, недостаточные оставляют тяжёлый центр. Правильную толщину помнит рука не хуже глаза.",
      },
    },
    {
      heading: { tr: "Fırındaki son doksan saniye", en: "The final ninety seconds", de: "Die letzten neunzig Sekunden", fr: "Les quatre-vingt-dix dernières secondes", ar: "التسعون ثانية الأخيرة", ru: "Последние девяносто секунд" },
      body: {
        tr: "Pizza taşa değdiği anda bütün hazırlık görünür hale gelir. Alt yüzey ile kubbenin sıcaklığı dengeli değilse taban pişmeden kenar kararır ya da tam tersi olur. Pizzaiolo pizzayı alevin yönüne göre çevirir, kabaran noktaları izler ve peyniri kurutmadan hamuru mühürler. Bu kısa süre acele değil, yoğun dikkat ister. Fırından çıkan pizza birkaç saniye dinlenir; yağ, peynir ve sos yeniden dengelenince servis edilir.",
        en: "The instant pizza meets the stone, every earlier decision becomes visible. If floor and dome temperatures are out of balance, the rim burns before the base sets—or the reverse. The pizzaiolo turns the pizza with the flame, watches each swelling point and seals the dough before the cheese dries. Those brief seconds demand concentration, not haste. After the oven, a short rest lets oil, cheese and sauce settle before service.",
        de: "Sobald die Pizza den Stein berührt, wird jede frühere Entscheidung sichtbar. Stimmen Boden- und Kuppelhitze nicht, verbrennt der Rand vor dem Boden oder umgekehrt. Der Pizzaiolo dreht zur Flamme, beobachtet jede Wölbung und schließt den Teig, bevor der Käse trocknet. Diese Sekunden verlangen Konzentration statt Eile. Danach ordnen sich Öl, Käse und Sauce kurz vor dem Servieren.",
        fr: "Dès que la pizza touche la pierre, toutes les décisions précédentes deviennent visibles. Si la sole et la voûte ne sont pas équilibrées, la corniche brûle avant le dessous, ou l’inverse. Le pizzaiolo tourne selon la flamme, observe chaque gonflement et saisit la pâte sans sécher le fromage. Ces secondes réclament de l’attention, pas de la précipitation. Une courte pause réunit ensuite huile, fromage et sauce.",
        ar: "حالما تلامس البيتزا الحجر تظهر نتيجة كل القرارات السابقة. إذا لم تتوازن حرارة الأرضية والقبة احترقت الحافة قبل القاعدة أو حدث العكس. يدير صانع البيتزا القرص مع اتجاه اللهب ويراقب الانتفاخ ويغلق العجين قبل أن يجف الجبن. تحتاج هذه الثواني إلى تركيز لا عجلة، ثم تستريح البيتزا قليلاً حتى تستقر الصلصة والجبن والزيت.",
        ru: "Как только пицца касается камня, становятся видны все прежние решения. Если жар пола и купола не сбалансирован, бортик сгорит раньше основания или наоборот. Пиццайоло поворачивает пиццу вслед за пламенем, следит за подъёмом и запечатывает тесто, не высушивая сыр. Эти секунды требуют внимания, а не спешки. Короткий отдых после печи вновь соединяет масло, сыр и соус.",
      },
    },
  ],
  "what-to-drink-with-neapolitan-pizza": [
    {
      heading: { tr: "Domates ve peynir için ayrı düşünmek", en: "Think differently for tomato and cheese", de: "Tomate und Käse getrennt denken", fr: "Penser différemment la tomate et le fromage", ar: "نفكر بالطماطم والجبن بشكل مختلف", ru: "Томат и сыр требуют разного подхода" },
      body: {
        tr: "Domatesin canlı asiditesi benzer tazelikte içeceklerle uzar; sütlü ve yağlı peynirler ise köpük, mineralite veya hafif acılıkla rahatlar. Margherita’da bu iki ihtiyacın ortasında temiz, kuru ve aroması ölçülü bir eşleşme ararız. Beyaz şarapta aşırı tropik meyve, kokteylde fazla şeker ya da sodada güçlü aroma malzemelerin ayrıntısını örtebilir. İyi seçim, pizzayı değiştirmez; onun çizgilerini daha görünür kılar.",
        en: "Tomato’s bright acidity is extended by equally fresh drinks, while milky, richer cheese benefits from bubbles, minerality or a gentle bitter edge. With Margherita we look for a clean, dry, measured answer between those needs. Overripe tropical fruit in wine, too much cocktail sugar or forceful flavoured soda can hide the ingredients. A good pairing does not alter the pizza; it simply makes its lines easier to see.",
        de: "Die lebendige Säure der Tomate wird von frischen Getränken verlängert, während milchiger Käse von Perlage, Mineralität oder feiner Bitterkeit profitiert. Zur Margherita suchen wir eine trockene, klare Antwort zwischen beiden Bedürfnissen. Tropische Überreife, zu viel Zucker oder starke Limonadenaromen verdecken Details. Eine gute Begleitung verändert die Pizza nicht, sondern zeichnet ihre Linien deutlicher.",
        fr: "L’acidité vive de la tomate se prolonge avec une boisson fraîche ; le fromage lacté et riche s’allège grâce aux bulles, à la minéralité ou à une amertume fine. Avec une Margherita, nous cherchons une réponse sèche, nette et mesurée. Fruit tropical trop mûr, sucre excessif ou soda très aromatique masquent les détails. Un bon accord ne transforme pas la pizza, il en révèle les lignes.",
        ar: "تمتد حموضة الطماطم مع مشروب منعش، بينما يرتاح الجبن الغني مع الفقاعات أو الطابع المعدني أو مرارة خفيفة. مع المارغريتا نبحث عن خيار جاف ونظيف ومتزن بين الحاجتين. الفاكهة الاستوائية المفرطة أو السكر الزائد أو الصودا القوية قد تغطي تفاصيل المكونات. التوافق الجيد لا يغيّر البيتزا، بل يجعل خطوطها أوضح.",
        ru: "Яркую кислотность томата продолжают столь же свежие напитки, а сливочному сыру помогают пузырьки, минеральность или мягкая горчинка. К «Маргарите» нужен сухой и чистый ответ между этими полюсами. Переспелые тропические тона, лишний сахар или навязчивый аромат газировки скрывают детали. Хорошая пара не меняет пиццу, а делает её линии яснее.",
      },
    },
    {
      heading: { tr: "Alkolsüz eşleşme de ciddiye alınır", en: "Alcohol-free pairing deserves equal care", de: "Alkoholfreie Begleitung verdient dieselbe Sorgfalt", fr: "L’accord sans alcool mérite le même soin", ar: "التوافق من دون كحول يستحق العناية نفسها", ru: "Безалкогольной паре нужна та же точность" },
      body: {
        tr: "İyi bir alkolsüz eşleşme yalnızca tatlı bir içecek sunmak değildir. İnce kabarcıklı maden suyu, limon kabuğu ve fesleğenle hazırlanan şekersiz bir soda ya da kuru karakterli fermente çay, yağlı dokuyu temizlerken pizzanın kokusunu korur. Sıcak baharatlı reçetelerde soğukluk ve asidite öne çıkar; mantarlı pizzalarda ise kavrulmuş çay ve bitkisel tonlar derinliği destekler. Ölçü yine aynıdır: bardak, bir sonraki lokmaya alan açmalıdır.",
        en: "A serious alcohol-free pairing is more than a sweet soft drink. Fine mineral water, unsweetened soda with lemon peel and basil, or a dry fermented tea can clean richer textures without erasing aroma. With spicy recipes, temperature and acidity lead; mushrooms welcome roasted tea and herbal depth. The measure remains the same: the glass should clear space for the next bite.",
        de: "Eine ernsthafte alkoholfreie Begleitung ist mehr als süße Limonade. Feines Mineralwasser, ungesüßte Soda mit Zitronenschale und Basilikum oder trockener fermentierter Tee reinigen reiche Texturen, ohne Aromen zu löschen. Zu Schärfe führen Kühle und Säure; Pilze mögen gerösteten Tee und Kräutertöne. Der Maßstab bleibt: Das Glas schafft Raum für den nächsten Bissen.",
        fr: "Un accord sans alcool sérieux ne se réduit pas à une boisson sucrée. Eau minérale fine, soda sans sucre au zeste de citron et basilic, ou thé fermenté sec nettoient les textures riches sans effacer les parfums. Avec le piquant, fraîcheur et acidité dominent ; les champignons accueillent le thé toasté et les notes végétales. Le verre doit toujours préparer la bouchée suivante.",
        ar: "التوافق الجاد من دون كحول ليس مشروباً حلواً فقط. المياه المعدنية الدقيقة أو صودا بلا سكر مع قشر الليمون والريحان أو شاي مخمّر جاف تنظف القوام الغني من دون إخفاء العطر. مع الوصفات الحارة تتقدم البرودة والحموضة، ومع الفطر تدعم نكهات الشاي المحمّص والأعشاب العمق. يبقى المقياس أن يفتح الكأس مساحة للقمة التالية.",
        ru: "Продуманная безалкогольная пара — не просто сладкий напиток. Тонкая минеральная вода, несладкая сода с цедрой и базиликом или сухой ферментированный чай очищают насыщенную текстуру, сохраняя аромат. К острому выходят вперёд холод и кислотность, к грибам — жареный чай и травы. Критерий тот же: бокал освобождает место для следующего кусочка.",
      },
    },
  ],
  "how-to-recognize-a-great-neapolitan-pizza": [
    {
      heading: { tr: "Alt yüzey, fırının imzasıdır", en: "The underside carries the oven’s signature", de: "Die Unterseite trägt die Signatur des Ofens", fr: "Le dessous porte la signature du four", ar: "القاعدة تحمل توقيع الفرن", ru: "Нижняя сторона хранит подпись печи" },
      body: {
        tr: "Pizzayı hafifçe kaldırıp tabanına bakmak çok şey anlatır. Düzgün dağılmış küçük koyu benekler yüksek ısı ile kısa pişirmenin izidir; geniş, siyah ve acı alanlar ise unun ya da tabanın yandığını gösterir. Merkez tamamen soluk kaldıysa taş yeterince sıcak olmayabilir. İyi taban kuru ama taş gibi sert değildir; katlandığında kırılmaz, tabağa bırakıldığında da hemen ıslanmaz.",
        en: "Lifting the pizza gently reveals a great deal. Small, evenly dispersed dark marks record high heat and a short bake; broad black bitter areas often mean burnt flour or base. A completely pale centre may signal a cool stone. A good underside is dry without becoming rigid: it folds without cracking and does not turn wet the moment it reaches the plate.",
        de: "Ein kurzer Blick unter die Pizza verrät viel. Kleine, gleichmäßig verteilte dunkle Punkte zeigen hohe Hitze und kurze Backzeit; breite schwarze, bittere Flächen deuten auf verbranntes Mehl oder Boden. Eine völlig blasse Mitte kann von einem zu kühlen Stein kommen. Ein guter Boden ist trocken, aber nicht starr: Er lässt sich falten und wird auf dem Teller nicht sofort nass.",
        fr: "Soulever doucement la pizza révèle beaucoup. De petits points sombres bien répartis témoignent d’une chaleur forte et d’une cuisson brève ; de larges zones noires et amères signalent souvent farine ou dessous brûlés. Un centre très pâle peut trahir une sole trop froide. Un bon dessous est sec sans être rigide : il plie sans casser et ne détrempe pas aussitôt dans l’assiette.",
        ar: "يكشف رفع البيتزا والنظر إلى أسفلها الكثير. البقع الداكنة الصغيرة والمتوازنة دليل حرارة عالية وخَبز قصير، أما المساحات السوداء الواسعة والمرّة فتشير إلى احتراق الدقيق أو القاعدة. وقد يعني المركز الشاحب أن الحجر غير ساخن بما يكفي. القاعدة الجيدة جافة من دون قسوة؛ تنثني بلا كسر ولا تبتل فور وصولها إلى الطبق.",
        ru: "Если осторожно приподнять пиццу, её основание многое расскажет. Мелкие равномерные тёмные отметины — след высокого жара и короткой выпечки; широкие чёрные горькие участки означают сгоревшую муку или тесто. Совсем бледный центр может говорить о холодном камне. Хорошее дно сухое, но не жёсткое: сгибается без трещин и не мокнет сразу на тарелке.",
      },
    },
    {
      heading: { tr: "Aroma, görüntüden önce gelir", en: "Aroma arrives before appearance", de: "Das Aroma kommt vor dem Bild", fr: "Le parfum arrive avant l’image", ar: "العطر يسبق الصورة", ru: "Аромат приходит раньше изображения" },
      body: {
        tr: "İyi pizza masaya gelirken önce sıcak ekmek, olgun domates, süt ve hafif duman kokusu taşır. Baskın maya, çiğ un, keskin yanık ya da ağır yağ kokusu dengenin bozulduğunu haber verir. İlk lokmada aromalar tek tek seçilir, birkaç saniye sonra aynı çizgide birleşir. Fotojenik bir kenar dikkat çekebilir; fakat gerçek kalite, burunla başlayan ve son lokmada temiz kalan bu bütünlüktür.",
        en: "Before it is seen closely, great pizza brings warm bread, ripe tomato, milk and gentle smoke to the table. Dominant yeast, raw flour, sharp burning or heavy oil suggests an imbalance. In the first bite each aroma can be read separately; seconds later they join one clear line. A photogenic rim may attract attention, but quality is the coherence that begins in the nose and stays clean through the final bite.",
        de: "Noch bevor man sie genau betrachtet, bringt gute Pizza warmes Brot, reife Tomate, Milch und feinen Rauch an den Tisch. Dominante Hefe, rohes Mehl, scharfer Brand oder schweres Öl verraten Unwucht. Im ersten Bissen sind Aromen einzeln lesbar und verbinden sich dann zu einer klaren Linie. Ein fotogener Rand fällt auf; Qualität ist die Geschlossenheit vom Duft bis zum letzten Bissen.",
        fr: "Avant même d’être regardée, une grande pizza apporte à table le pain chaud, la tomate mûre, le lait et une fumée légère. Levure dominante, farine crue, brûlé agressif ou huile lourde annoncent un déséquilibre. Chaque parfum se lit d’abord séparément puis rejoint une ligne claire. Une belle corniche attire l’œil ; la qualité est cette cohérence qui commence au nez et reste nette jusqu’à la fin.",
        ar: "قبل النظر إليها عن قرب تحمل البيتزا الجيدة رائحة الخبز الدافئ والطماطم الناضجة والحليب والدخان الخفيف. رائحة الخميرة القوية أو الدقيق النيئ أو الاحتراق الحاد أو الزيت الثقيل تعلن خللاً. في اللقمة الأولى تظهر الروائح منفصلة ثم تجتمع في خط واضح. قد تلفت الحافة الجميلة النظر، لكن الجودة هي هذا الانسجام من الأنف حتى اللقمة الأخيرة.",
        ru: "Ещё до близкого взгляда хорошая пицца приносит аромат тёплого хлеба, зрелого томата, молока и лёгкого дыма. Доминирующие дрожжи, сырая мука, резкая гарь или тяжёлое масло выдают дисбаланс. В первом кусочке ноты различимы, а затем собираются в одну линию. Фотогеничный бортик привлекает взгляд, но качество — это цельность от первого аромата до чистого финала.",
      },
    },
  ],
};
